/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import entidades.Funcionario;
import entidades.Usuario;

/**
 *
 * @author mateu
 */
public class TelaHomeFuncionarioView extends javax.swing.JFrame {
    
    private TelaCadastroFuncionarioView cadastroFuncionario;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaHomeFuncionarioView.class.getName());
    private Usuario funcionario = new Funcionario();
    private TelaSituacaoEstoqueView telaSituacaoEstoque;
    private TelaRegistrarVendaView telaRegistrarVenda;
    /**
     * Creates new form TelaHomeView
     */
    public TelaHomeFuncionarioView(Usuario umUsu) {
        initComponents();
        this.funcionario = umUsu;
        tfUsuario.setText(funcionario.getNome());
        tfPonto.setText("");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jbCadastrarProduto = new javax.swing.JButton();
        jbRegistrarVenda = new javax.swing.JButton();
        jbSituacaoEstoque = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblPonto = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        tfPonto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btVerConta = new javax.swing.JButton();
        btSairConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Funcionario");

        jbCadastrarProduto.setBackground(new java.awt.Color(205, 255, 255));
        jbCadastrarProduto.setText("Cadastrar produto");
        jbCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarProdutoActionPerformed(evt);
            }
        });

        jbRegistrarVenda.setBackground(new java.awt.Color(205, 255, 255));
        jbRegistrarVenda.setText("Registrar Venda");
        jbRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarVendaActionPerformed(evt);
            }
        });

        jbSituacaoEstoque.setBackground(new java.awt.Color(205, 255, 255));
        jbSituacaoEstoque.setText("Situação Estoque");
        jbSituacaoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSituacaoEstoqueActionPerformed(evt);
            }
        });

        lblUsuario.setText("Usuário:");

        lblPonto.setText("Ponto:");

        tfUsuario.setEditable(false);

        tfPonto.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Padaria SisMaik");

        btVerConta.setBackground(new java.awt.Color(205, 255, 255));
        btVerConta.setText("Ver Conta");
        btVerConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerContaActionPerformed(evt);
            }
        });

        btSairConta.setBackground(new java.awt.Color(205, 255, 255));
        btSairConta.setText("Sair da Conta");
        btSairConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPonto)
                            .addComponent(lblUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbRegistrarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSituacaoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btVerConta, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(btSairConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRegistrarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVerConta))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrarProduto)
                    .addComponent(btSairConta))
                .addGap(18, 18, 18)
                .addComponent(jbSituacaoEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPonto)
                    .addComponent(tfPonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarProdutoActionPerformed
        TelaCadastroProdutoView telaCadastroProduto = new TelaCadastroProdutoView();
        telaCadastroProduto.setVisible(true);
    }//GEN-LAST:event_jbCadastrarProdutoActionPerformed

    private void jbRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarVendaActionPerformed
        telaRegistrarVenda = new TelaRegistrarVendaView(this.funcionario);
        telaRegistrarVenda.setVisible(true);
    }//GEN-LAST:event_jbRegistrarVendaActionPerformed

    private void jbSituacaoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSituacaoEstoqueActionPerformed
        TelaSituacaoEstoqueView telaSituacaoEstoque = new TelaSituacaoEstoqueView(funcionario);
        telaSituacaoEstoque.setVisible(true);
    }//GEN-LAST:event_jbSituacaoEstoqueActionPerformed

    private void btVerContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerContaActionPerformed
        TelaDetalhesDaContaView telaDetalhesConta = new TelaDetalhesDaContaView(funcionario);
        telaDetalhesConta.setVisible(true);
    }//GEN-LAST:event_btVerContaActionPerformed

    private void btSairContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairContaActionPerformed
        TelaLoginCadastroView telaLogin = new TelaLoginCadastroView();
        telaLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btSairContaActionPerformed
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSairConta;
    private javax.swing.JButton btVerConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbCadastrarProduto;
    private javax.swing.JButton jbRegistrarVenda;
    private javax.swing.JButton jbSituacaoEstoque;
    private javax.swing.JLabel lblPonto;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField tfPonto;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables

}
