/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import Controller.UsuarioController;
import Excecoes.usuarioInvalido;
import entidades.Admin;
import entidades.Cliente;
import entidades.Funcionario;
import entidades.Usuario;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import trabalhopadaria.UsuarioDAO;

/**
 *
 * @author mateu
 */
public class TelaLoginCadastroView extends javax.swing.JFrame {
    
    private TelaHomeClienteView telaHome;
    private UsuarioDAO usDao;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLoginCadastroView.class.getName());
    private UsuarioController usuarioController;

    /**
     * Creates new form TelaLoginView
     */
    public TelaLoginCadastroView() {
        initComponents();
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnPanel, BorderLayout.WEST);
        getContentPane().add(pnHome, BorderLayout.CENTER);
        pnHome.setVisible(false);
        usuarioController = new UsuarioController();
        usDao = new UsuarioDAO();
        usDao.salvar(new Admin("admin", "admin", "admin", "admin"));
        setLocationRelativeTo(null);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPanel = new javax.swing.JPanel();
        lbInt2 = new javax.swing.JLabel();
        lbInt1 = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();
        lbCadastro = new javax.swing.JLabel();
        btCadastro = new javax.swing.JButton();
        pnHome = new javax.swing.JPanel();
        tpHome = new javax.swing.JTabbedPane();
        pnCadastro = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        lbNomeCadastro = new javax.swing.JLabel();
        tfNomeCadastro = new javax.swing.JTextField();
        lbCpfCadastro = new javax.swing.JLabel();
        tfCpfCadastro = new javax.swing.JTextField();
        lbTelefoneCadastro = new javax.swing.JLabel();
        tfTelefoneCadastro = new javax.swing.JTextField();
        lbSenhaCadastro = new javax.swing.JLabel();
        tfSenhaCadastro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnLogin = new javax.swing.JPanel();
        lbCpfLogin = new javax.swing.JLabel();
        tfCpfLogin = new javax.swing.JTextField();
        lbSenhaLogin = new javax.swing.JLabel();
        tfSenhaLogin = new javax.swing.JTextField();
        btLogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Inicial");

        lbInt2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbInt2.setText("Padaria SisMaik");
        lbInt2.setAutoscrolls(true);

        lbInt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbInt1.setText("Bem Vindo a");
        lbInt1.setAutoscrolls(true);

        lbLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbLogin.setText("Já possui login?");
        lbLogin.setAutoscrolls(true);

        btLogin.setText("Login");
        btLogin.setAutoscrolls(true);
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        lbCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbCadastro.setText("Primeira vez aqui?");
        lbCadastro.setAutoscrolls(true);

        btCadastro.setText("Cadastro");
        btCadastro.setAutoscrolls(true);
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPanelLayout = new javax.swing.GroupLayout(pnPanel);
        pnPanel.setLayout(pnPanelLayout);
        pnPanelLayout.setHorizontalGroup(
            pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnPanelLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(btLogin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCadastro)
                            .addGap(21, 21, 21))
                        .addGroup(pnPanelLayout.createSequentialGroup()
                            .addComponent(lbLogin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCadastro)))
                    .addGroup(pnPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbInt2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPanelLayout.createSequentialGroup()
                                .addComponent(lbInt1)
                                .addGap(48, 48, 48)))
                        .addGap(66, 66, 66)))
                .addGap(18, 18, 18))
        );
        pnPanelLayout.setVerticalGroup(
            pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbInt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInt2)
                .addGap(18, 18, 18)
                .addGroup(pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogin)
                    .addComponent(lbCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLogin)
                    .addComponent(btCadastro))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pnHome.setBackground(new java.awt.Color(255, 204, 204));

        tpHome.setBackground(new java.awt.Color(153, 255, 102));

        btSalvar.setText("Cadastrar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        lbNomeCadastro.setText("Nome:");

        lbCpfCadastro.setText("CPF:");

        lbTelefoneCadastro.setText("Telefone:");

        lbSenhaCadastro.setText("Senha:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jLabel4.setText("Formato: XX 9XXXX-XXXX");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jLabel3.setText("Formato: 111-222-333.44");

        javax.swing.GroupLayout pnCadastroLayout = new javax.swing.GroupLayout(pnCadastro);
        pnCadastro.setLayout(pnCadastroLayout);
        pnCadastroLayout.setHorizontalGroup(
            pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSalvar))
                    .addGroup(pnCadastroLayout.createSequentialGroup()
                        .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTelefoneCadastro)
                            .addComponent(tfTelefoneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCpfCadastro)
                            .addComponent(tfSenhaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addGroup(pnCadastroLayout.createSequentialGroup()
                                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(lbSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnCadastroLayout.setVerticalGroup(
            pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCadastroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCadastro)
                    .addComponent(lbCpfCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefoneCadastro)
                    .addComponent(lbSenhaCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTelefoneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addContainerGap())
        );

        tpHome.addTab("Cadastro", pnCadastro);

        lbCpfLogin.setText("CPF:");

        lbSenhaLogin.setText("Senha:");

        btLogar.setText("Logar");
        btLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLoginLayout = new javax.swing.GroupLayout(pnLogin);
        pnLogin.setLayout(pnLoginLayout);
        pnLoginLayout.setHorizontalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCpfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(lbCpfLogin)
                    .addComponent(tfSenhaLogin)
                    .addComponent(lbSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginLayout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(btLogar)
                .addContainerGap())
        );
        pnLoginLayout.setVerticalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbCpfLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCpfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSenhaLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btLogar)
                .addContainerGap())
        );

        tpHome.addTab("Login", pnLogin);

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpHome)
                .addContainerGap())
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomeLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(tpHome, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(477, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 353, Short.MAX_VALUE)
                    .addComponent(pnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 190, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        pnHome.setVisible(true);
        tpHome.setSelectedIndex(0);
        revalidate();
        pack();
    }//GEN-LAST:event_btCadastroActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        String nome = tfNomeCadastro.getText();
        String cpf = tfCpfCadastro.getText();
        String telefone = tfTelefoneCadastro.getText();
        String senha = tfSenhaCadastro.getText();
        try{
            Cliente clienteSalvo = usuarioController.salvarNovoCliente(nome, cpf, telefone, senha);
            JOptionPane.showMessageDialog(null, "Cliente " + clienteSalvo.getNome() + " cadastrado com sucesso!");
            tfNomeCadastro.setText("");
            tfCpfCadastro.setText("");
            tfTelefoneCadastro.setText("");
            tfSenhaCadastro.setText("");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro ao Cadastrar");
        }            
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        pnHome.setVisible(true);
        tpHome.setSelectedIndex(1);
        revalidate();
        pack();
    }//GEN-LAST:event_btLoginActionPerformed

    private void btLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogarActionPerformed
        String cpf = tfCpfLogin.getText();
        String senha = tfSenhaLogin.getText();

        try {
            // Valida se usuário existe
            Usuario usuarioAutenticado = usuarioController.autenticarUsuario(cpf, senha);

            if (usuarioAutenticado != null) {
                if (usuarioAutenticado instanceof Cliente) {
                    Cliente clienteLogado = (Cliente) usuarioAutenticado;
                    // Abre a tela Home do Cliente
                    telaHome = new TelaHomeClienteView(clienteLogado); // Passa o cliente
                    telaHome.setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Bem vindo de volta\nCliente " + usuarioAutenticado.getNome());
                } 
                else if (usuarioAutenticado instanceof Admin) {
                     TelaHomeAdminView telaHomeAdmin = new TelaHomeAdminView(usuarioAutenticado);
                     telaHomeAdmin.setVisible(true);
                     this.dispose();
                     JOptionPane.showMessageDialog(null, "Bem vindo de volta\nAdmin " + usuarioAutenticado.getNome());
                     
                 } else if (usuarioAutenticado instanceof Funcionario) {
                     TelaHomeFuncionarioView telaHomeFuncionario = new TelaHomeFuncionarioView(usuarioAutenticado);
                     telaHomeFuncionario.setVisible(true);
                     this.dispose();
                     JOptionPane.showMessageDialog(null, "Bem vindo de volta\nFuncionário " + usuarioAutenticado.getNome());
                 }
                 else {
                     JOptionPane.showMessageDialog(this, "Tipo de usuário não suportado para login nesta tela.", "Acesso Negado", JOptionPane.WARNING_MESSAGE);
                 }
                
            } else {
                // Falha na autenticação
                throw new usuarioInvalido("CPF ou Senha incorretos!");
            }
            
        } catch (usuarioInvalido ex) {
            JOptionPane.showMessageDialog(this, "Erro de Login: " + ex.getMessage());
        }
    }//GEN-LAST:event_btLogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLoginCadastroView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btLogar;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbCadastro;
    private javax.swing.JLabel lbCpfCadastro;
    private javax.swing.JLabel lbCpfLogin;
    private javax.swing.JLabel lbInt1;
    private javax.swing.JLabel lbInt2;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbNomeCadastro;
    private javax.swing.JLabel lbSenhaCadastro;
    private javax.swing.JLabel lbSenhaLogin;
    private javax.swing.JLabel lbTelefoneCadastro;
    private javax.swing.JPanel pnCadastro;
    private javax.swing.JPanel pnHome;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JPanel pnPanel;
    private javax.swing.JTextField tfCpfCadastro;
    private javax.swing.JTextField tfCpfLogin;
    private javax.swing.JTextField tfNomeCadastro;
    private javax.swing.JTextField tfSenhaCadastro;
    private javax.swing.JTextField tfSenhaLogin;
    private javax.swing.JTextField tfTelefoneCadastro;
    private javax.swing.JTabbedPane tpHome;
    // End of variables declaration//GEN-END:variables
}
