/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import entidades.Admin;
import entidades.Usuario;

/**
 *
 * @author mateu
 */
public class TelaHomeAdminView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaHomeAdminView.class.getName());
    private Usuario admin = new Admin();
    private TelaCadastroFuncionarioView telaCadastroFuncionario;
    private TelaDeletarUsuarioView telaDeletarUsuario;
    private TelaSituacaoEstoqueView telaSituacaoEstoque;
    private TelaCadastroProdutoView telaCadastrarProduto;
    private TelaRegistrarVendaView telaRegistrarVenda;
    
    /**
     * Creates new form TelaHomeView
     */
    public TelaHomeAdminView(Usuario umUsu) {
        initComponents();
        this.admin = umUsu;
        tfUsuario.setText(admin.getNome());
        tfPonto.setText("");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jbCadastrarProduto = new javax.swing.JButton();
        jbRegistrarVenda = new javax.swing.JButton();
        jbSituacaoEstoque = new javax.swing.JButton();
        jbCadastrarFuncionario = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblPonto = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        tfPonto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbVisualizarUsuarios = new javax.swing.JButton();
        btVerConta = new javax.swing.JButton();
        btSairConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home admin");

        jbCadastrarProduto.setBackground(new java.awt.Color(205, 255, 255));
        jbCadastrarProduto.setText("Cadastrar produto");
        jbCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarProdutoActionPerformed(evt);
            }
        });

        jbRegistrarVenda.setBackground(new java.awt.Color(205, 255, 255));
        jbRegistrarVenda.setText("Registrar Venda");
        jbRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarVendaActionPerformed(evt);
            }
        });

        jbSituacaoEstoque.setBackground(new java.awt.Color(205, 255, 255));
        jbSituacaoEstoque.setText("Situação Estoque");
        jbSituacaoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSituacaoEstoqueActionPerformed(evt);
            }
        });

        jbCadastrarFuncionario.setBackground(new java.awt.Color(205, 255, 255));
        jbCadastrarFuncionario.setText("Cadastrar Funcionário");
        jbCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarFuncionarioActionPerformed(evt);
            }
        });

        lblUsuario.setText("Usuário:");

        lblPonto.setText("Ponto:");

        tfUsuario.setEditable(false);

        tfPonto.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Padaria SisMaik");

        jButton1.setBackground(new java.awt.Color(205, 255, 255));
        jButton1.setText("Visualizar Vendas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbVisualizarUsuarios.setBackground(new java.awt.Color(205, 255, 255));
        jbVisualizarUsuarios.setText("Visualizar Usuários");
        jbVisualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarUsuariosActionPerformed(evt);
            }
        });

        btVerConta.setBackground(new java.awt.Color(205, 255, 255));
        btVerConta.setText("Ver Conta");
        btVerConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerContaActionPerformed(evt);
            }
        });

        btSairConta.setBackground(new java.awt.Color(205, 255, 255));
        btSairConta.setText("Sair da Conta");
        btSairConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPonto)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 316, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSituacaoEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbRegistrarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbVisualizarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btVerConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSairConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbRegistrarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrarProduto)
                    .addComponent(jbVisualizarUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSituacaoEstoque)
                    .addComponent(btVerConta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrarFuncionario)
                    .addComponent(btSairConta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPonto)
                    .addComponent(tfPonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarProdutoActionPerformed
        TelaCadastroProdutoView telaCadastrarProduto = new TelaCadastroProdutoView();
        telaCadastrarProduto.setVisible(true);
    }//GEN-LAST:event_jbCadastrarProdutoActionPerformed

    private void jbRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarVendaActionPerformed
        telaRegistrarVenda = new TelaRegistrarVendaView(this.admin);
        telaRegistrarVenda.setVisible(true);
    }//GEN-LAST:event_jbRegistrarVendaActionPerformed

    private void jbCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarFuncionarioActionPerformed
        TelaCadastroFuncionarioView telaCadastroFuncionario = new TelaCadastroFuncionarioView();
        telaCadastroFuncionario.setVisible(true);
    }//GEN-LAST:event_jbCadastrarFuncionarioActionPerformed

    private void jbSituacaoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSituacaoEstoqueActionPerformed
        TelaSituacaoEstoqueView telaSituacaoEstoque = new TelaSituacaoEstoqueView(admin);
        telaSituacaoEstoque.setVisible(true);
    }//GEN-LAST:event_jbSituacaoEstoqueActionPerformed

    private void jbVisualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarUsuariosActionPerformed
        TelaVisualizarUsuarios telaVisualizarUsuarios = new TelaVisualizarUsuarios();
        telaVisualizarUsuarios.setVisible(true);
    }//GEN-LAST:event_jbVisualizarUsuariosActionPerformed

    private void btVerContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerContaActionPerformed
        TelaDetalhesDaContaView telaDetalhesConta = new TelaDetalhesDaContaView(admin);
        telaDetalhesConta.setVisible(true);
    }//GEN-LAST:event_btVerContaActionPerformed

    private void btSairContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairContaActionPerformed
        TelaLoginCadastroView telaLogin = new TelaLoginCadastroView();
        telaLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btSairContaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaVisualizarVendasView telaVisualizarVendas = new TelaVisualizarVendasView();
        telaVisualizarVendas.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSairConta;
    private javax.swing.JButton btVerConta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbCadastrarFuncionario;
    private javax.swing.JButton jbCadastrarProduto;
    private javax.swing.JButton jbRegistrarVenda;
    private javax.swing.JButton jbSituacaoEstoque;
    private javax.swing.JButton jbVisualizarUsuarios;
    private javax.swing.JLabel lblPonto;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField tfPonto;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables

}
